### ISSUE TITLE
Remove <py3.10 restriction

### ISSUE THREAD

**Issue by pearu** [heavyai/heavyai#31]
https://github.com/heavyai/heavyai/blob/d23eb702fa8c392a2115e73f12141c60965fbe21/environment.yml#L10

https://github.com/heavyai/heavyai/blob/d23eb702fa8c392a2115e73f12141c60965fbe21/environment_gpu.yml#L10

**Comment by tupui** [comment]
FYI in the pyproject.toml I went ahead before the release and removed it since it was just a conda thing to restrict to at the time.

**Comment by tupui** [comment]
Do we also want to keep support for python 3.7?

**Comment by pearu** [comment]
> Do we also want to keep support for python 3.7?

If 3.7 is not a blocker to anything then the default answer would be yes.

@andrewseidl @mikehinchey do we expect that there will be Python 3.7 users for heavyai?

**Comment by tupui** [comment]
FYI, geopandas and other dependencies such as NumPy dropped python 3.7 in their latest releases.
